### ISSUE TITLE
KeReadyThread

### ISSUE THREAD

**Issue by mereckaj** [chaostheory88/revengineering#1]
Just a question.

Any chance of being able to see your disassembled code for this routine ?

I have found some other people posting solutions to this problem but they all seem to have a different KeReadyThread functions compared to me. Your solution , almost,matches mine (Windows 7 x86_32 though).
[Different?](https://cloud.githubusercontent.com/assets/6073373/3817516/abe0a16a-1cd8-11e4-9515-58210d278f0f.jpg)

Your method does some checking if it can call on KiFastReadyThread where as most peoples solutions seem to be a mix of both (KeReadyThread and KiFastReadyThread).

Also if this is the case, then can I ask for an explanation why you access Thread.SystemAffinityActive ? In my disassembly of the _KTHREAD it is a single bit value ( You check if it is not 7 ? )

I only suspect the following from my code:

mov     eax,dword ptr [esi+50h]
Above instruction accesses the _KTHREAD Structure. 0x50 is the offset for the _KAPC_STATE(0x40)->Process(0x10).

mov     ecx,dword ptr [eax+74h]
This instruction accesses the _KPROCESS->StackCount.Value variable.

So I am led to believe that either you have different disassembly code, which is quite possible, and in your code Thread.SystemAffinityActive is not a single bit value or you may have made a mistake.

**Comment by chaostheory88** [comment]
Hi, maybe you're right the problem with my disassembly is that it was taken from a win7 x86_64 and I haven't it anymore. I dunno if I have saved it somewhere, I have forgotten to put into into the exercise solution. By the way, I've tested what you said about the offsets [esi+50h] and [eax+74h] on win7 x86_32 and your reasoning seems to be correct. I suppose my code is wrong because I don't think the difference could be so huge between x86_32 and x86_64 in regards of this function.

**Comment by baderj** [comment]
I checked on Windows 8 64bit. The disassembly looks almost the same as the one of chaostheory, only the offsets are different. I can confirm that the two instructions retrieve _KPROCESS->StackCount, but at least on Windows 8 this is a 4 Byte:

0x000 State           : Pos 0, 3 Bits
0x000 StackCount : Pos 3, 29 Bits

The comparison with 7 checks if the State is "111" (I don't know what that means though).

**Comment by mereckaj** [comment]
I tried it out on windows 7 7600 x86_64 and the code is similar enough (Different offsets but they access same structs). KiFastReadyThread is a lot different though(And very big).

In my version it is also a 4byte value.
lkd> dt _KSTACK_COUNT
nt!_KSTACK_COUNT
   +0x000 Value            : Int4B
   +0x000 State            : Pos 0, 3 Bits
   +0x000 StackCount       : Pos 3, 29 Bits

Thanks for clearing this up. Glad you replied.

**Comment by chaostheory88** [comment]
Thank you guys, I'll fix my code as soon as possible. I cannot realize how I have made a so big mistake with the struct's offsets. Thank you for posting the issue @mereckaj.
